#!/bin/bash

current_branch=$(git symbolic-ref --short HEAD)

git s
git add .
git s
git commit --amend --no-edit
git push --force-with-lease -u origin $current_branch

# Check if the push was successful
if [ $? -eq 0 ]; then
	response="Changes successfully pushed!"
	echo -e "\033[32m$response\033[0m"
else
	response="Failed to push changes!"
	echo -e "\033[31m$response\033[0m"
fi
